#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

git_dir="${TMP_MOUNT_PATH}/opt/git"
project_config_dir="${git_dir}/mos-infra/project-config"

if [[ -d "${project_config_dir}" ]]; then
    sudo rm -rf "${project_config_dir}"
fi

if [[ ! -d "${git_dir}" ]]; then
    sudo mkdir -p "${git_dir}"
fi

sudo chown -R $(whoami) "${git_dir}"
mkdir -p "${project_config_dir}"

pushd "${project_config_dir}"
git clone ssh://review.fuel-infra.org:29418/mos-infra/project-config.git .
git checkout mosi
popd

cat "${project_config_dir}/gerrit/projects.yaml"