#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

project_config_dir="${TMP_MOUNT_PATH}/etc/project-config"
if [[ -d "${project_config_dir}" ]]; then
    sudo rm -rf "${project_config_dir}"
fi

sudo mkdir -p "${project_config_dir}"
sudo chown $(whoami) "${project_config_dir}"

pushd "${project_config_dir}"
git clone ssh://review.fuel-infra.org:29418/mos-infra/project-config.git .
popd
