#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail


mkdir -p ${TMP_MOUNT_PATH}/opt/git
git clone ssh://review.fuel-infra.org:29418/mosi-infra/project-config ${TMP_MOUNT_PATH}/opt/git/project-config
