#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

sudo mkdir -p "${TMP_MOUNT_PATH}/opt/nodepool-scripts"
sudo chmod 777 "${TMP_MOUNT_PATH}/opt/nodepool-scripts"
sudo cp -r /etc/nodepool/scripts/* "${TMP_MOUNT_PATH}/opt/nodepool-scripts"

sudo mkdir -p "${TMP_MOUNT_PATH}/etc/nodepool"
sudo chmod 777 "${TMP_MOUNT_PATH}/etc/nodepool"
sudo cp -r /etc/nodepool/scripts/* "${TMP_MOUNT_PATH}/etc/nodepool"
