#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# WARNING
# This script does potentially dangerous thing!
# It copies *entire* directory /home/nodepool/.ssh from nodepool
# host to every slave, into root's home directory.
# This is needed to allow slave to clone git repositories via SSH.

sudo cp -r /home/nodepool/.ssh "${TMP_MOUNT_PATH}/root"
