#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

    cat > /etc/cloud/cloud.cfg.d/99-apt-preserve-sources-list.cfg <<EOF
apt_preserve_sources_list: true
EOF
