#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cat << EOF > "/etc/apt/sources.list.d/ubuntu.list"
deb http://archive.ubuntu.com/ubuntu ${DIB_RELEASE} main universe
deb http://archive.ubuntu.com/ubuntu ${DIB_RELEASE}-updates main universe
EOF

apt-get update
