#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

NODEPOOL_SSH_KEY=${NODEPOOL_SSH_KEY:-''}

set -eu
set -o pipefail

adduser --gecos Jenkins-user --disabled-password --quiet jenkins

mkdir -p /home/jenkins/.ssh
if [[ -n "${NODEPOOL_SSH_KEY}" ]]; then
    echo "ssh-rsa ${NODEPOOL_SSH_KEY}" > /home/jenkins/.ssh/authorized_keys
fi

chown -R jenkins:jenkins /home/jenkins/.ssh
